### ISSUE TITLE
Build with GHC 8

### ISSUE THREAD

**Issue by niteria** [jstolarek/tasty-program#6]
Relaxing the bound on `base` was enough to make it build. Can you relax the bound and make a new release?

**Comment by jstolarek** [comment]
I pushed the fix to the repo. Will try to release a new version to Hackage later today.

**Comment by niteria** [comment]
Thank you! Would you consider adding `tasty-program` to stackage?

**Comment by jstolarek** [comment]
I could do that if you consider it useful. But that won't happen today :-)

**Comment by jstolarek** [comment]
I published version 1.0.5 to Hackage. As it turns out Hackage requires that an upper bound on base is specified.

**Comment by niteria** [comment]
Thank you!
